services:
  postgres:
    image: 'postgres:latest'
    container_name:  integracao_db
    env_file: '.env'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5432:5432'
  minio:
    image: 'minio/minio'
    container_name: integracao_minio
    command: server /data
    env_file: '.env'
    environment:
      - 'MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}'
      - 'MINIO_SECRET_KEY=${MINIO_SECRET_KEY}'
    ports:
      - '9000:9000'
    volumes:
      - minio_data:/data

volumes:
  minio_data:
