spring:
  application:
    name: implementacao_back-end

# App
server:
  servlet:
    application-display-name: implementacao_back-end
    context-path: /implementacao_back-end
  address: 0.0.0.0
  port: 8080

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # Configurações de logging
  logging:
    level:
      org.springframework.security: DEBUG
      dev.senzalla: DEBUG


minio:
  url: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:fotos}
  expiry: ${MINIO_EXPIRY:300} # 5 minutos em segundos

app:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:8081,http://localhost:3000}
  jwt:
    secret: ${JWT_SECRET:umaChaveMuitoLongaComPeloMenos64CaracteresParaHS512QueDeveSerMantidaEmSegredo}
    expiration: ${JWT_EXPIRATION:300000} # 5 minutos em milissegundos
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000} # 24 horas em milissegundos

# Configurações do Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true
    disable-swagger-default-url: true
  show-actuator: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  paths-to-match: /api/** 